mantisbt:
  image: xlrl/mantisbt:latest
  environment:
    - MANTIS_TIMEZONE=Europe/Berlin
    - MANTIS_ENABLE_ADMIN=0
  ports:
    - "8989:80"
  links:
    - mysql
  restart: always
  volumes:
    - ./config:/var/www/html/config
    - ./custom:/var/www/html/custom

mysql:
  image: mariadb:latest
  environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=bugtracker
    - MYSQL_USER=mantis
    - MYSQL_PASSWORD=mantis
  restart: always
  volumes:
    - ./mysql:/var/lib/mysql

postgres:
  image: postgres:latest
  environment:
    - POSTGRES_USER=root
    - POSTGRES_PASSWORD=root
  restart: always
